---
title: "Assignment 9"
author: "Charuvi Begwani, Aijing Li"
date: "4/1/2022"
output: html_document
---

```{r}
library(here)
library(tidyverse)
library(sf)
library(knitr)
library(kableExtra)
library(survey)
library(srvyr)
```
#Transit fare per unlinked trip
```{r}
cost_per_ride <- 32521480 / 23559294

cost_per_ride
```

#Driving cost per minute

```{r}
temp <- tempfile()
download.file("https://nhts.ornl.gov/assets/2016/download/csv.zip", temp)

vehs <- read_csv(unz(temp, "vehpub.csv"), 
                 show_col_types = FALSE) %>%
  filter(HH_CBSA == "41620")

trips <- read_csv(unz(temp, "trippub.csv"), 
                      show_col_types = FALSE) %>%
  filter(HH_CBSA == "41620")

car_trips <- trips %>%
  filter(PSGR_FLG == "02") 
  
unlink(temp)
```

```{r}
car_trips_svy <- car_trips %>%
  as_survey(weights = WTTRDFIN)

veh_svy <- vehs %>%
  as_survey(weights = WTHHFIN)

total_time <- car_trips_svy %>%
  summarise(total_time = survey_total(TRVLCMIN))

kable(total_time, format.args = list(big.mark = ",",
                                     scientific = FALSE))

```

#calculate total fuel expenditure

```{r}
total_gas_cost <- veh_svy %>%
  summarise(total_cost = survey_total(GSTOTCST))

kable(total_gas_cost, format.args = list(big.mark = ","))
```
#calculate fuel cost per minute

```{r}
cost_per_minute <- total_gas_cost$total_cost[1] / total_time$total_time[1] 

cost_per_minute
```

#Costs per trip
##Load travel skims
```{r}
skims <- here("existing",
              "data",
              "skims.csv") %>%
  read_csv(show_col_types = FALSE)

head(skims, 5) %>%
  kable() %>%
  kable_styling() %>%
  scroll_box(width = "500px", height = "320px")
```
##Cost of transit and cost of driving
```{r}
skims <- skims %>%
  mutate(drive_cost = car_time * cost_per_minute) %>%
  mutate(transit_cost = n_rides * cost_per_ride)
```

##estimate cost of carpooling
```{r}
skims <- skims %>%
  mutate(carpool_cost = drive_cost / 2.42)
```

#Estimate existing modeshare for Salt Lake MSA
```{r}
trips <- trips %>%
  mutate(home_based = case_when(WHYTO == "01" ~ TRUE,
                                WHYTO == "02" ~ TRUE,
                                WHYFROM == "01" ~ TRUE,
                                WHYFROM == "02" ~ TRUE,
                                TRUE ~ FALSE)) %>%
  mutate(work = ifelse(WHYTO == "03" | WHYFROM == "03", TRUE, FALSE)) %>%
  mutate(purpose = case_when(home_based & work ~ "HBW",
                            home_based ~ "HBO",
                            TRUE ~ "NHB")) %>%
  mutate(mode = case_when(TRPTRANS == "01" ~ "walk",
                          TRPTRANS == "02" ~ "bike",
                          TRPTRANS == "03" & NUMONTRP > 1 ~ "HOV",
                          TRPTRANS == "04" & NUMONTRP > 1 ~ "HOV",
                          TRPTRANS == "05" & NUMONTRP > 1 ~ "HOV",
                          TRPTRANS == "06" & NUMONTRP > 1 ~ "HOV",
                          TRPTRANS == "08" & NUMONTRP > 1 ~ "HOV",
                          TRPTRANS == "17" & NUMONTRP > 1 ~ "HOV",
                          TRPTRANS == "18" & NUMONTRP > 1 ~ "HOV",
                          TRPTRANS == "03" ~ "SOV",
                          TRPTRANS == "04" ~ "SOV",
                          TRPTRANS == "05" ~ "SOV",
                          TRPTRANS == "06" ~ "SOV",
                          TRPTRANS == "08" ~ "SOV",
                          TRPTRANS == "17" ~ "SOV",
                          TRPTRANS == "18" ~ "SOV",
                          TRPTRANS == "10" ~ "transit",
                          TRPTRANS == "11" ~ "transit",
                          TRPTRANS == "12" ~ "transit",
                          TRPTRANS == "13" ~ "transit",
                          TRPTRANS == "16" ~ "transit",
                          TRUE ~ "other")) %>%
  filter(mode != "other")
```

#Generate trips by mode
```{r}
trips_svy <- trips %>%
  as_survey(weights = WTTRDFIN)

mode_by_purpose <- trips_svy %>%
  group_by(purpose, mode) %>%
  survey_tally() %>%
  select(-n_se) %>%
  pivot_wider(names_from = mode,
              values_from = n,
              names_prefix = "n_",) %>%
  mutate(n_trips = n_bike + n_SOV + n_HOV + n_transit + n_walk) %>%
  mutate(pct_bike = n_bike / n_trips) %>%
  mutate(pct_SOV = n_SOV / n_trips) %>%
  mutate(pct_HOV = n_HOV / n_trips) %>%
  mutate(pct_walk = n_walk / n_trips) %>%
  mutate(pct_transit = n_transit / n_trips) %>%
  select(purpose, pct_bike, pct_SOV, pct_HOV, pct_transit, pct_walk)

mode_by_purpose
```

