---
title: "Assignment 8"
author: "Aijing Li, Charuvi Begwani"
date: "3/24/2022"
output: html_document
---

## Set-up and Load Data
```{r, message=FALSE,warning=FALSE}
library(here)
library(tidyverse)
library(sf)
library(survey)
library(srvyr)
library(od)
library(ggspatial)
library(scenRios)
```

```{r}
zones <- here("existing",
              "data",
              "zone_data.csv") %>%
  read_csv()

skims <- here("existing",
              "data",
              "skims.csv") %>%
  read_csv()
```
```{r, message=FALSE, warning=FALSE, results='hide'}
temp <- tempfile()
download.file("https://nhts.ornl.gov/assets/2016/download/csv.zip", temp)

trips <- read_csv(unz(temp, "trippub.csv"), 
                      show_col_types = FALSE) %>%
  filter(HH_CBSA == "41620")

unlink(temp)

trips <- trips %>%
  mutate(home_based = case_when(WHYTO == "01" ~ TRUE,
                                WHYTO == "02" ~ TRUE,
                                WHYFROM == "01" ~ TRUE,
                                WHYFROM == "02" ~ TRUE,
                                TRUE ~ FALSE)) %>%
  mutate(work = ifelse(WHYTO == "03" | WHYFROM == "03", TRUE, FALSE)) %>%
  mutate(purpose = case_when(home_based & work ~ "HBW",
                            home_based ~ "HBO",
                            TRUE ~ "NHB"))
```

```{r}
trips_svy <- trips %>%
  as_survey(weights = WTTRDFIN)

ttime_by_purpose <- trips_svy %>%
  group_by(purpose) %>%
  summarise(avg_time = survey_mean(TRVLCMIN))

ttime_by_purpose
```
```{r}
skims <- skims %>%
  mutate(min_time = pmin(transit_time, 
                         car_time,
                         bike_time,
                         walk_time,
                         na.rm = TRUE)) %>%
  # set minimum travel time to 1 if it isn't on the diagonal
  mutate(min_time = case_when(fromId == toId ~ min_time,
                              min_time < 1 ~ 1,
                              TRUE ~ min_time))
```

# Calculate friction factors

## Gamma function

I recommend you use the gamma function with parameters from NCHRP 716 for all three trip purposes. You'll find it converges much faster.

```{r}
skims <- skims %>%
  mutate(F_HBW = min_time^-0.503*exp(-0.078*min_time),
         F_HBO = min_time^-3.993*exp(-0.019*min_time),
         F_NHB = min_time^-3.345*exp(-0.003*min_time))
```



## Estimate travel flows
```{r}
HBO_dist <- grvty_balancing(od_zones = zones,
                            friction = skims,
                            zone_id = "GEOID",
                            zone_o = "hbo_prod",
                            zone_d = "hbo_attr_bal",
                            friction_o_id = "fromId",
                            friction_d_id = "toId",
                            friction_factor = "F_HBO",
                            tolerance = 5,
                            max_iter = 50000)
```


```{r}
HBW_dist <- grvty_balancing(od_zones = zones,
                            friction = skims,
                            zone_id = "GEOID",
                            zone_o = "hbw_prod",
                            zone_d = "hbw_attr_bal",
                            friction_o_id = "fromId",
                            friction_d_id = "toId",
                            friction_factor = "F_HBW",
                            tolerance = 5,
                            max_iter = 50000)
```


```{r}
NHB_dist <- grvty_balancing(od_zones = zones,
                            friction = skims,
                            zone_id = "GEOID",
                            zone_o = "nhb_prod",
                            zone_d = "nhb_attr_bal",
                            friction_o_id = "fromId",
                            friction_d_id = "toId",
                            friction_factor = "F_NHB",
                            tolerance = 5,
                            max_iter = 50000)
```